const jobsData = [
  {
    id: 1,
    title: "Game Designer",
    company: "Ubisoft",
    location: "Montreal, Canada",
    country: "Canada",
    city: "Montreal",
    region: "North America",
    category: "Gaming",
    workMode: "Hybrid",
    jobType: "Full-time",
    level: "Mid Level",
    source: "LinkedIn",
    posted: "2 days ago",
    postedDays: 2,
    salary: "$70k - $95k",
    applyLink: "https://example.com/apply/1",
    description:
      "Design and iterate on core gameplay loops, progression, and player-facing features for a live game.",
    lat: 45.5017,
    lng: -73.5673,
  },
  {
    id: 2,
    title: "Architect",
    company: "Foster + Partners",
    location: "London, UK",
    country: "UK",
    city: "London",
    region: "Europe",
    category: "Architecture",
    workMode: "Onsite",
    jobType: "Full-time",
    level: "Junior",
    source: "Company Website",
    posted: "1 day ago",
    postedDays: 1,
    salary: "£32k - £40k",
    applyLink: "https://example.com/apply/2",
    description:
      "Support design development, visual communication, and technical coordination across architecture projects.",
    lat: 51.5074,
    lng: -0.1278,
  },
  {
    id: 3,
    title: "Level Designer",
    company: "EA Games",
    location: "California, USA",
    country: "USA",
    city: "Los Angeles",
    region: "North America",
    category: "Gaming",
    workMode: "Hybrid",
    jobType: "Contract",
    level: "Senior",
    source: "Indeed",
    posted: "5 days ago",
    postedDays: 5,
    salary: "$90k - $115k",
    applyLink: "https://example.com/apply/3",
    description:
      "Create and balance player journeys, mission flow, and environmental pacing for a multiplayer title.",
    lat: 34.0522,
    lng: -118.2437,
  },
  {
    id: 4,
    title: "Urban Designer",
    company: "Gensler",
    location: "Berlin, Germany",
    country: "Germany",
    city: "Berlin",
    region: "Europe",
    category: "Architecture",
    workMode: "Onsite",
    jobType: "Full-time",
    level: "Mid Level",
    source: "LinkedIn",
    posted: "3 days ago",
    postedDays: 3,
    salary: "€42k - €55k",
    applyLink: "https://example.com/apply/4",
    description:
      "Contribute to large-scale urban design projects through concept studies, diagrams, and masterplanning support.",
    lat: 52.52,
    lng: 13.405,
  },
  {
    id: 5,
    title: "3D Environment Artist",
    company: "Riot Games",
    location: "Singapore",
    country: "Singapore",
    city: "Singapore",
    region: "Asia",
    category: "Gaming",
    workMode: "Onsite",
    jobType: "Full-time",
    level: "Senior",
    source: "Company Website",
    posted: "6 days ago",
    postedDays: 6,
    salary: "SGD 78k - 102k",
    applyLink: "https://example.com/apply/5",
    description:
      "Build high-quality game environments in collaboration with design and art teams for a stylized experience.",
    lat: 1.3521,
    lng: 103.8198,
  },
  {
    id: 6,
    title: "Computational Designer",
    company: "Zaha Hadid Architects",
    location: "Dubai, UAE",
    country: "UAE",
    city: "Dubai",
    region: "Middle East",
    category: "Architecture",
    workMode: "Onsite",
    jobType: "Full-time",
    level: "Mid Level",
    source: "Archinect",
    posted: "Today",
    postedDays: 0,
    salary: "AED 16k - 22k / month",
    applyLink: "https://example.com/apply/6",
    description:
      "Develop parametric workflows, support concept generation, and bridge design intent with computational tools.",
    lat: 25.2048,
    lng: 55.2708,
  },
  {
    id: 7,
    title: "Remote Gameplay Designer",
    company: "Supercell",
    location: "Remote",
    country: "Remote",
    city: "Remote",
    region: "Remote",
    category: "Gaming",
    workMode: "Remote",
    jobType: "Full-time",
    level: "Senior",
    source: "Company Website",
    posted: "4 days ago",
    postedDays: 4,
    salary: "€85k - €110k",
    applyLink: "https://example.com/apply/7",
    description:
      "Own feature ideation, balancing, and player motivation systems for a global live-ops product.",
    lat: null,
    lng: null,
  },
  {
    id: 8,
    title: "Remote Architectural Designer",
    company: "BIG",
    location: "Remote",
    country: "Remote",
    city: "Remote",
    region: "Remote",
    category: "Architecture",
    workMode: "Remote",
    jobType: "Contract",
    level: "Mid Level",
    source: "LinkedIn",
    posted: "2 days ago",
    postedDays: 2,
    salary: "$45 - $60 / hr",
    applyLink: "https://example.com/apply/8",
    description:
      "Support concept packages, visualization, and research-led design tasks across international projects.",
    lat: null,
    lng: null,
  },
  {
    id: 9,
    title: "Technical Artist",
    company: "Epic Games",
    location: "Seoul, South Korea",
    country: "South Korea",
    city: "Seoul",
    region: "Asia",
    category: "Gaming",
    workMode: "Hybrid",
    jobType: "Full-time",
    level: "Mid Level",
    source: "LinkedIn",
    posted: "1 day ago",
    postedDays: 1,
    salary: "₩58M - ₩74M",
    applyLink: "https://example.com/apply/9",
    description:
      "Bridge art and engineering pipelines while improving tools, performance, and asset implementation.",
    lat: 37.5665,
    lng: 126.978,
  },
  {
    id: 10,
    title: "Landscape Architect",
    company: "VOGT",
    location: "Zurich, Switzerland",
    country: "Switzerland",
    city: "Zurich",
    region: "Europe",
    category: "Architecture",
    workMode: "Onsite",
    jobType: "Full-time",
    level: "Mid Level",
    source: "Company Website",
    posted: "7 days ago",
    postedDays: 7,
    salary: "CHF 72k - 86k",
    applyLink: "https://example.com/apply/10",
    description:
      "Support concept and detail design for landscape-led public realm and ecological projects.",
    lat: 47.3769,
    lng: 8.5417,
  },
  {
    id: 11,
    title: "UI/UX Game Designer",
    company: "Gameloft",
    location: "Barcelona, Spain",
    country: "Spain",
    city: "Barcelona",
    region: "Europe",
    category: "Gaming",
    workMode: "Hybrid",
    jobType: "Full-time",
    level: "Junior",
    source: "Indeed",
    posted: "Today",
    postedDays: 0,
    salary: "€30k - €38k",
    applyLink: "https://example.com/apply/11",
    description:
      "Design player flows, menu systems, and intuitive user interfaces for mobile and PC games.",
    lat: 41.3851,
    lng: 2.1734,
  },
  {
    id: 12,
    title: "Architectural Assistant",
    company: "BDP",
    location: "Dublin, Ireland",
    country: "Ireland",
    city: "Dublin",
    region: "Europe",
    category: "Architecture",
    workMode: "Hybrid",
    jobType: "Full-time",
    level: "Junior",
    source: "LinkedIn",
    posted: "8 days ago",
    postedDays: 8,
    salary: "€32k - €39k",
    applyLink: "https://example.com/apply/12",
    description:
      "Support design teams with visual communication, coordination packages, and concept development.",
    lat: 53.3498,
    lng: -6.2603,
  },
];

export default jobsData;
